
export const mockDepreciationData = [
    {
      vin: 'CR1565',
      purchaseDate: '2020-01-01',
      purchasePrice: 60000,
      depreciationMethod: 'Straight-line',
      usefulLifeYears: 10,
      salvageValue: 5000,
      depreciationRate: 10,
      accumulatedDepreciation: 18000,
      currentBookValue: 42000,
      depreciationPeriod: 'Year 3',
      depreciationExpense: 6000,
      notesRemarks: 'Regular depreciation.',
    },
    {
      vin: 'DL6389',
      purchaseDate: '2019-06-15',
      purchasePrice: 80000,
      depreciationMethod: 'Declining Balance',
      usefulLifeYears: 8,
      salvageValue: 8000,
      depreciationRate: 25,
      accumulatedDepreciation: 40000,
      currentBookValue: 40000,
      depreciationPeriod: 'Year 4',
      depreciationExpense: 10000,
      notesRemarks: 'Accelerated depreciation.',
    },
    {
      vin: 'PX4793',
      purchaseDate: '2018-05-23',
      purchasePrice: 75000,
      depreciationMethod: 'Straight-line',
      usefulLifeYears: 12,
      salvageValue: 6000,
      depreciationRate: 8,
      accumulatedDepreciation: 24000,
      currentBookValue: 51000,
      depreciationPeriod: 'Year 5',
      depreciationExpense: 7500,
      notesRemarks: 'Normal wear and tear.',
    },
    {
      vin: 'LK5278',
      purchaseDate: '2021-02-11',
      purchasePrice: 90000,
      depreciationMethod: 'Declining Balance',
      usefulLifeYears: 7,
      salvageValue: 10000,
      depreciationRate: 20,
      accumulatedDepreciation: 36000,
      currentBookValue: 54000,
      depreciationPeriod: 'Year 3',
      depreciationExpense: 18000,
      notesRemarks: 'Accelerated depreciation due to usage.',
    },
    {
      vin: 'FT3829',
      purchaseDate: '2020-07-09',
      purchasePrice: 50000,
      depreciationMethod: 'Straight-line',
      usefulLifeYears: 15,
      salvageValue: 7000,
      depreciationRate: 6.67,
      accumulatedDepreciation: 13340,
      currentBookValue: 36660,
      depreciationPeriod: 'Year 4',
      depreciationExpense: 3330,
      notesRemarks: 'Steady usage, regular depreciation.',
    },
    {
      vin: 'MT4891',
      purchaseDate: '2017-09-20',
      purchasePrice: 100000,
      depreciationMethod: 'Straight-line',
      usefulLifeYears: 10,
      salvageValue: 10000,
      depreciationRate: 10,
      accumulatedDepreciation: 70000,
      currentBookValue: 30000,
      depreciationPeriod: 'Year 7',
      depreciationExpense: 10000,
      notesRemarks: 'Extended use, minimal downtime.',
    },
    {
      vin: 'YT5982',
      purchaseDate: '2022-03-19',
      purchasePrice: 120000,
      depreciationMethod: 'Declining Balance',
      usefulLifeYears: 6,
      salvageValue: 15000,
      depreciationRate: 30,
      accumulatedDepreciation: 72000,
      currentBookValue: 48000,
      depreciationPeriod: 'Year 2',
      depreciationExpense: 36000,
      notesRemarks: 'High initial depreciation.',
    }
  ];
  