export const maintenanceRecords = [
    {
      date: "2024-09-15",
      vin: "1HGCM82633A004352",
      driverName: "John Doe",
      maintenanceType: "Oil Change",
      descriptionOfWorkDone: "Changed engine oil and oil filter.",
      partsReplacedServiced: ["Engine Oil", "Oil Filter"],
      costOfMaintenance: 150,
      serviceProvider: "Speedy Auto Repair",
      technicianName: "Mike Johnson",
      serviceLocation: "123 Main St, Anytown, USA",
      nextScheduledMaintenance: "2024-12-15",
      notesRemarks: "Engine in good condition. No additional repairs needed.",
    },
    {
      date: "2024-10-01",
      vin: "1HGCM82633A123456",
      driverName: "Jane Smith",
      maintenanceType: "Tire Rotation",
      descriptionOfWorkDone: "Rotated all four tires.",
      partsReplacedServiced: ["Tires"],
      costOfMaintenance: 50,
      serviceProvider: "QuickFix Tire Shop",
      technicianName: "Sam Williams",
      serviceLocation: "456 Elm St, OtherTown, USA",
      nextScheduledMaintenance: "2025-01-01",
      notesRemarks: "Tires showing normal wear and tear.",
    },
    {
      date: "2024-10-10",
      vin: "2B3KA43RX8H241063",
      driverName: "Robert Brown",
      maintenanceType: "Engine Check",
      descriptionOfWorkDone: "Engine diagnostics and minor tuning.",
      partsReplacedServiced: ["Spark Plugs"],
      costOfMaintenance: 250,
      serviceProvider: "ProTech Garage",
      technicianName: "Sarah Green",
      serviceLocation: "789 Maple Ave, BigCity, USA",
      nextScheduledMaintenance: "2025-04-10",
      notesRemarks: "Replaced worn-out spark plugs. Recommended coolant check in 6 months.",
    },
    {
      date: "2024-11-05",
      vin: "JH4DA9370LS007350",
      driverName: "Alice Johnson",
      maintenanceType: "Brake Inspection",
      descriptionOfWorkDone: "Inspected and replaced front brake pads.",
      partsReplacedServiced: ["Brake Pads"],
      costOfMaintenance: 300,
      serviceProvider: "Brake Masters",
      technicianName: "Tom Lewis",
      serviceLocation: "321 Oak St, SmallTown, USA",
      nextScheduledMaintenance: "2025-05-05",
      notesRemarks: "Front brakes replaced. Rear brakes in good condition.",
    },
    {
      date: "2024-11-20",
      vin: "1GNEK13ZX3R298298",
      driverName: "David White",
      maintenanceType: "Tire Replacement",
      descriptionOfWorkDone: "Replaced all four tires.",
      partsReplacedServiced: ["Tires"],
      costOfMaintenance: 800,
      serviceProvider: "All-Terrain Tires",
      technicianName: "Chris Adams",
      serviceLocation: "654 Pine Rd, RuralTown, USA",
      nextScheduledMaintenance: "2025-11-20",
      notesRemarks: "New tires installed. Balanced and aligned wheels.",
    }
  ];
  