import { WasteRevenue } from "@/lib/validation";

export const mockWasteRevenueData: WasteRevenue[] = [
  {
    vin: "CR1234",
    date: "2024-10-01",
    totalBinsCollected: 100,
    wasteCollectionType: "Plastic",
    revenuePerBin: 5,
    totalRevenue: 500,
    driverName: "John Doe",
    collectionType: "Regular",
  },
  {
    vin: "DL5678",
    date: "2024-10-02",
    totalBinsCollected: 150,
    wasteCollectionType: "Metal",
    revenuePerBin: 8,
    totalRevenue: 1200,
    driverName: "Jane Smith",
    collectionType: "On Demand",
  },
  {
    vin: "CD4926",
    date: "2024-09-30",
    totalBinsCollected: 75,
    wasteCollectionType: "Organic",
    revenuePerBin: 3,
    totalRevenue: 225,
    driverName: "Mark Johnson",
    collectionType: "Regular",
  },
  {
    vin: "BK1290",
    date: "2024-10-03",
    totalBinsCollected: 200,
    wasteCollectionType: "Mixed",
    revenuePerBin: 6,
    totalRevenue: 1200,
    driverName: "Alice Cooper",
    collectionType: "Regular",
  },
  {
    vin: "XT7834",
    date: "2024-10-04",
    totalBinsCollected: 120,
    wasteCollectionType: "Plastic",
    revenuePerBin: 4.5,
    totalRevenue: 540,
    driverName: "Paul Simon",
    collectionType: "On Demand",
  },
  {
    vin: "LB3849",
    date: "2024-09-29",
    totalBinsCollected: 50,
    wasteCollectionType: "Glass",
    revenuePerBin: 7,
    totalRevenue: 350,
    driverName: "Mary Jane",
    collectionType: "Regular",
  },
  {
    vin: "CR7777",
    date: "2024-10-01",
    totalBinsCollected: 90,
    wasteCollectionType: "Metal",
    revenuePerBin: 8,
    totalRevenue: 720,
    driverName: "Jake Peralta",
    collectionType: "On Demand",
  },
  {
    vin: "MK9374",
    date: "2024-10-05",
    totalBinsCollected: 110,
    wasteCollectionType: "Paper",
    revenuePerBin: 5,
    totalRevenue: 550,
    driverName: "Terry Jeffords",
    collectionType: "Regular",
  },
  {
    vin: "NB4628",
    date: "2024-09-28",
    totalBinsCollected: 140,
    wasteCollectionType: "Organic",
    revenuePerBin: 3.5,
    totalRevenue: 490,
    driverName: "Amy Santiago",
    collectionType: "On Demand",
  },
  {
    vin: "TY4736",
    date: "2024-10-06",
    totalBinsCollected: 60,
    wasteCollectionType: "Plastic",
    revenuePerBin: 4,
    totalRevenue: 240,
    driverName: "Rosa Diaz",
    collectionType: "Regular",
  },
];
