import { WasteBinsCollected } from "@/lib/validation";

export const wasteBinsCollectedData: WasteBinsCollected[] = [
  {
    vin: "CR 1565",
    route: "Route A",
    date: "2024-09-01",
    wasteBinsCollected: 120,
    tripDuration: "4 hours",
    driverName: "John Doe",
    fuelConsumed: 30,
    notesRemarks: "Completed on schedule",
  },
  {
    vin: "DL 6389",
    route: "Route B",
    date: "2024-09-01",
    wasteBinsCollected: 85,
    tripDuration: "3.5 hours",
    driverName: "Jane Smith",
    fuelConsumed: 25,
    notesRemarks: "Additional recycling bins collected",
  },
  {
    vin: "CD 4926",
    route: "Route C",
    date: "2024-09-02",
    wasteBinsCollected: 50,
    tripDuration: "5 hours",
    driverName: "Mark Johnson",
    fuelConsumed: 35,
    notesRemarks: "Delayed due to traffic",
  },
  {
    vin: "AB 1234",
    route: "Route D",
    date: "2024-09-03",
    wasteBinsCollected: 100,
    tripDuration: "6 hours",
    driverName: "Emily Davis",
    fuelConsumed: 40,
    notesRemarks: "Smooth trip with no delays",
  },
  {
    vin: "XY 5678",
    route: "Route E",
    date: "2024-09-04",
    wasteBinsCollected: 70,
    tripDuration: "4.5 hours",
    driverName: "Michael Brown",
    fuelConsumed: 28,
    notesRemarks: "Additional stops made for recycling",
  },
  {
    vin: "UV 3456",
    route: "Route F",
    date: "2024-09-05",
    wasteBinsCollected: 60,
    tripDuration: "3 hours",
    driverName: "Sarah Lee",
    fuelConsumed: 22,
    notesRemarks: "Minor traffic delays",
  },
  {
    vin: "MN 7890",
    route: "Route G",
    date: "2024-09-06",
    wasteBinsCollected: 90,
    tripDuration: "6.5 hours",
    driverName: "Chris Miller",
    fuelConsumed: 45,
    notesRemarks: "Longer trip duration due to route change",
  },
  {
    vin: "QR 4321",
    route: "Route H",
    date: "2024-09-07",
    wasteBinsCollected: 110,
    tripDuration: "5.5 hours",
    driverName: "David Wilson",
    fuelConsumed: 38,
    notesRemarks: "Bins collected efficiently",
  },
  {
    vin: "VW 2468",
    route: "Route I",
    date: "2024-09-08",
    wasteBinsCollected: 95,
    tripDuration: "4 hours",
    driverName: "Lisa Adams",
    fuelConsumed: 32,
    notesRemarks: "Extra waste due to festival event",
  },
  {
    vin: "OP 9753",
    route: "Route J",
    date: "2024-09-09",
    wasteBinsCollected: 130,
    tripDuration: "7 hours",
    driverName: "Steven Clark",
    fuelConsumed: 50,
    notesRemarks: "High collection due to weekend rush",
  },
];
