export const mockData = [
    {
      insuranceID: 'IC1234',
      vin: 'CR1567',
      incidentDate: '2024-09-01',
      claimAmount: 10000,
      claimStatus: 'Pending',
      claimDate: '2024-09-02',
      insuranceProvider: 'XYZ Insurance',
      driverInvolved: 'John Doe',
      incidentDescription: 'Minor collision',
      claimResolutionDate: '',
      resolutionNotes: '',
    },
    {
      insuranceID: 'IC5678',
      vin: 'DL6389',
      incidentDate: '2024-08-20',
      claimAmount: 5000,
      claimStatus: 'Resolved',
      claimDate: '2024-08-21',
      insuranceProvider: 'ABC Insurance',
      driverInvolved: 'Jane Smith',
      incidentDescription: 'Damage to windshield',
      claimResolutionDate: '2024-08-25',
      resolutionNotes: 'Fully covered',
    },
    {
      insuranceID: 'IC9101',
      vin: 'CD4926',
      incidentDate: '2024-07-15',
      claimAmount: 12500,
      claimStatus: 'In Process',
      claimDate: '2024-07-16',
      insuranceProvider: 'DEF Insurance',
      driverInvolved: 'Mark Johnson',
      incidentDescription: 'Engine malfunction',
      claimResolutionDate: '',
      resolutionNotes: '',
    },
    {
      insuranceID: 'IC4444',
      vin: 'ER7821',
      incidentDate: '2024-06-11',
      claimAmount: 15000,
      claimStatus: 'Pending',
      claimDate: '2024-06-12',
      insuranceProvider: 'GH Insurance',
      driverInvolved: 'Samuel Green',
      incidentDescription: 'Fire damage',
      claimResolutionDate: '',
      resolutionNotes: '',
    },
    {
      insuranceID: 'IC5555',
      vin: 'FT6732',
      incidentDate: '2024-05-25',
      claimAmount: 8000,
      claimStatus: 'Resolved',
      claimDate: '2024-05-26',
      insuranceProvider: 'JKL Insurance',
      driverInvolved: 'Emily Brown',
      incidentDescription: 'Theft',
      claimResolutionDate: '2024-05-30',
      resolutionNotes: 'Partially covered',
    },
    {
      insuranceID: 'IC6666',
      vin: 'HV9284',
      incidentDate: '2024-04-19',
      claimAmount: 6000,
      claimStatus: 'In Process',
      claimDate: '2024-04-20',
      insuranceProvider: 'MNO Insurance',
      driverInvolved: 'Lucas White',
      incidentDescription: 'Hit by another vehicle',
      claimResolutionDate: '',
      resolutionNotes: '',
    },
  ];
  