import { licenseCostSchema } from "@/lib/validation";
import { z } from "zod"
type LicenseCost = z.infer<typeof licenseCostSchema>;


export const licenseCostData: LicenseCost[] = [
    {
      vin: "CR1565",
      licenseType: "Commercial",
      licenseNumber: "LC123456",
      issuingAuthority: "DVLA",
      licenseIssueDate: "2023-01-10",
      licenseExpiryDate: "2024-01-10",
      licenseCost: 500,
      renewalCost: 450,
      paymentDate: "2023-01-10",
      paymentMode: "Direct Debit",
      finesPenalties: 0,
      licensingLocation: "Accra Branch",
      notesRemarks: "License renewed before expiry.",
    },
    {
      vin: "DL6389",
      licenseType: "Personal",
      licenseNumber: "LP789012",
      issuingAuthority: "DVLA",
      licenseIssueDate: "2022-06-20",
      licenseExpiryDate: "2023-06-20",
      licenseCost: 350,
      renewalCost: 300,
      paymentDate: "2022-06-20",
      paymentMode: "Cash",
      finesPenalties: 50,
      licensingLocation: "Kumasi Office",
      notesRemarks: "Late renewal due to processing delays.",
    },
    {
      vin: "CD4926",
      licenseType: "Commercial",
      licenseNumber: "LC563489",
      issuingAuthority: "DVLA",
      licenseIssueDate: "2021-11-15",
      licenseExpiryDate: "2022-11-15",
      licenseCost: 600,
      renewalCost: 550,
      paymentDate: "2021-11-15",
      paymentMode: "Cash",
      finesPenalties: 0,
      licensingLocation: "Accra Branch",
      notesRemarks: "No issues with renewal.",
    },
    {
      vin: "MN3647",
      licenseType: "Personal",
      licenseNumber: "LP245980",
      issuingAuthority: "DVLA",
      licenseIssueDate: "2023-03-01",
      licenseExpiryDate: "2024-03-01",
      licenseCost: 450,
      renewalCost: 400,
      paymentDate: "2023-03-01",
      paymentMode: "Mobile Payment",
      finesPenalties: 30,
      licensingLocation: "Takoradi Branch",
      notesRemarks: "Fined for late renewal.",
    },
    {
      vin: "FG7384",
      licenseType: "Personal",
      licenseNumber: "LP568492",
      issuingAuthority: "DVLA",
      licenseIssueDate: "2020-09-10",
      licenseExpiryDate: "2021-09-10",
      licenseCost: 300,
      renewalCost: 250,
      paymentDate: "2020-09-10",
      paymentMode: "Mobile Payment",
      finesPenalties: 20,
      licensingLocation: "Kumasi Office",
      notesRemarks: "Minor delay in processing.",
    },
  ];
  